[package]
name = "vam-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
vam-authority = { path = "../../crates/authority" }

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
