[package]
name = "vam-dev"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "vam-dev"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
vam-application = { path = "../../crates/application" }
vam-core = { path = "../../crates/core" }
vam-deployment = { path = "../../crates/deployment" }
vam-secrets = { path = "../../crates/secrets" }
vam-storage = { path = "../../crates/storage" }

[lints]
workspace = true
