[package]
name = "vam-authority-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
uuid.workspace = true
zeroize.workspace = true
vam-authority = { path = "../authority" }
vam-core = { path = "../core" }
vam-ssh = { path = "../ssh" }

[dev-dependencies]
tokio.workspace = true
vam-protocol = { path = "../protocol" }

[lints]
workspace = true
